### ISSUE TITLE
Individual wall cover setting

### ISSUE THREAD

**Issue by lucaspicerni** [trioderegion/dnd5e-helpers#290]
First of all, I'm sorry if I'm doing something wrong. When opening the settings of a wall and selecting the option "no cover" and saving, the setting resets to the default value "full cover". Tested in an empty world and only with the D&D5e Helpers module active. Foundry 9.255, D&D5 1.6.1 and D&D5e Helpers 4.1.3.

https://user-images.githubusercontent.com/95550238/167199669-8d990719-2637-4147-9ee1-2ac4cca20e54.mp4

**Comment by trioderegion** [comment]
Thank you for the report and video. Something indeed is not working correctly. I thought I fixed this in 4.1.0, but I guess not!  I'll look into this -- sorry for the trouble.

**Comment by trioderegion** [comment]
Has this been resolved? My issue tracking has gotten a bit messy 😅

**Comment by lucaspicerni** [comment]
No, unfortunately the error persists. Tested today, version 4.1.3.

**Comment by trioderegion** [comment]
I think i'll be receiving a small PR for an additional Wild Magic Variant in the next day or two. I will see if I can squash this irritating bug in the process. Sorry for the delay...

**Comment by trioderegion** [comment]
Ah ha! It appears to only occur with "No Cover" setting, in which it resets to "Full Cover". Will get this fixed in 4.2.0.
