### ISSUE TITLE
Hide Magic Surge rolls

### ISSUE THREAD

**Issue by majcrew35** [trioderegion/dnd5e-helpers#59]
Please consider expanding the "Blind table draw" option to include an option for "Blind wild surge rolls" to keep them hidden from players. 

Thanks!

**Comment by trioderegion** [comment]
Resolved in 1.9.3

**Comment by majcrew35** [comment]
Just checked 1.9.3, still don't see the option to hide the wild surge roll. Can only hide the wild magic table draw.

**Comment by trioderegion** [comment]
I'm so sorry. It was late and I confused myself with the whispering of *Cover Results*...not Wild Magic Surge.

Re-opening ticket with great shame. Will prioritize this as a form of apology :)

**Comment by trioderegion** [comment]
I have partially implemented this in 1.9.4. However, it is not perfect (as noted in the changelog). To do this properly requires a bit more rework. #63 encompasses this rework.
